name: sample_go_router
version: 1.0.0+1

environment:
  sdk: ^3.6.0-216.1.beta
dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.6.1
  gap: ^3.0.1
  go_router: ^14.6.1
  pedantic_mono: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.3
  go_router_builder: ^2.7.1

flutter:
  uses-material-design: true
