name: sample_1
description: "sample 1 project"
version: 1.0.0+1

environment:
  sdk: ^3.6.0-216.1.beta
dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  gap: ^3.0.1
  go_router: ^14.6.1
  hooks_riverpod: ^2.6.1
  pedantic_mono: any
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.6.3
  go_router_builder: ^2.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
